### ISSUE TITLE
[SETTINGS] builtins causing problems in /admin route.

### ISSUE THREAD

**Issue by Ilopesr** [mixxorz/slippers#65]
### settings.py
```py
TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [BASE_DIR / "templates"],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
				"apps.properties.context_processors.cart",
			],
			"builtins": ["slippers.templatetags.slippers"],
		},
	},
]
```
### error
![image](https://github.com/mixxorz/slippers/assets/89506748/c0f7d760-6b4e-4574-ab11-7d78b9dd0d5d)
### description
```shell
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 5.0.6
Python Version: 3.12.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'apps.core',
 'apps.accounts',
 'apps.properties',
 'slippers',
 'django_filters',
 'django_browser_reload',
 'django_extensions',
 'django_htmx',
 'anymail']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_browser_reload.middleware.BrowserReloadMiddleware',
 'django_htmx.middleware.HtmxMiddleware']


Template error:
In template C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\contrib\admin\templates\admin\index.html, error at line 41
   Invalid block tag on line 41: 'endfilter', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
   31 :             {% for entry in admin_log %}
   32 :             <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
   33 :                 <span class="visually-hidden">{% if entry.is_addition %}{% translate 'Added:' %}{% elif entry.is_change %}{% translate 'Changed:' %}{% elif entry.is_deletion %}{% translate 'Deleted:' %}{% endif %}</span>
   34 :                 {% if entry.is_deletion or not entry.get_admin_url %}
   35 :                     {{ entry.object_repr }}
   36 :                 {% else %}
   37 :                     <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
   38 :                 {% endif %}
   39 :                 <br>
   40 :                 {% if entry.content_type %}
   41 :                     <span class="mini quiet">{% filter capfirst %}{{ entry.content_type.name }} {% endfilter %} </span>
   42 :                 {% else %}
   43 :                     <span class="mini quiet">{% translate 'Unknown content' %}</span>
   44 :                 {% endif %}
   45 :             </li>
   46 :             {% endfor %}
   47 :             </ul>
   48 :             {% endif %}
   49 :     </div>
   50 : </div>
   51 : {% endblock %}


Traceback (most recent call last):
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ^^^^^^^^^^^^^^^^^^

During handling of the above exception ('endfilter'), another exception occurred:
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\defaulttags.py", line 975, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\Desktop\propertie.dev\.venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
    ^

Exception Type: TemplateSyntaxError at /admin/
Exception Value: Invalid block tag on line 41: 'endfilter', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?

```

**Comment by mixxorz** [comment]
This looks like a project specific issue and not something wrong with slippers. But if you could provide a minimal reproducible example, that would help pin this down.
